name: SonarCloud Analysis

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: SonarCloud
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'Práctica 3 - Taller Final/web'

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache de Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Ejecutar análisis con SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=web \
            -Dsonar.organization=ibaimoya \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
